#!/bin/bash
# Git版本管理脚本
# 管理内核版本的Git标签和分支

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
KERNEL_SRC="${SCRIPT_DIR}/Xiaomi_Kernel_OpenSource-zijin-s-oss"
VERSION_FILE="${SCRIPT_DIR}/KERNEL_VERSION"

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step() { echo -e "${BLUE}[STEP]${NC} $1"; }

# 获取当前版本
get_current_version() {
    cat "$VERSION_FILE" 2>/dev/null || echo "unknown"
}

# 列出所有版本标签
list_versions() {
    log_info "Available kernel versions:"
    echo ""
    
    # 主仓库的标签
    echo "Main repository tags:"
    cd "$SCRIPT_DIR"
    git tag -l "kernel-v*" | sort -V | tail -20
    
    echo ""
    
    # 内核源码的标签
    if [ -d "$KERNEL_SRC/.git" ]; then
        echo "Kernel source tags:"
        cd "$KERNEL_SRC"
        git tag -l "v5.4.*" | sort -V | tail -20
    fi
}

# 创建版本标签
create_tag() {
    local version=$1
    local message=${2:-"Kernel version $version"}
    
    if [ -z "$version" ]; then
        version=$(get_current_version)
    fi
    
    local date=$(date +%Y%m%d)
    local tag_name="kernel-v${version}-${date}"
    
    cd "$SCRIPT_DIR"
    
    # 检查标签是否已存在
    if git tag -l | grep -q "^${tag_name}$"; then
        log_warn "Tag $tag_name already exists"
        return 1
    fi
    
    log_step "Creating tag: $tag_name"
    
    # 创建主仓库标签
    git tag -a "$tag_name" -m "$message
    
Build date: $(date)
Kernel version: $version
Generated by version manager
"
    
    log_info "Tag created successfully"
    echo "$tag_name"
}

# 创建版本分支
create_branch() {
    local version=$1
    local branch_name="kernel-${version}"
    
    if [ -z "$version" ]; then
        log_error "Please specify version"
        return 1
    fi
    
    cd "$SCRIPT_DIR"
    
    # 检查分支是否已存在
    if git branch -a | grep -q "$branch_name"; then
        log_warn "Branch $branch_name already exists"
        return 1
    fi
    
    log_step "Creating branch: $branch_name"
    
    git checkout -b "$branch_name"
    
    log_info "Branch created successfully"
    echo "$branch_name"
}

# 切换到指定版本
switch_version() {
    local version=$1
    
    if [ -z "$version" ]; then
        log_error "Please specify version"
        return 1
    fi
    
    cd "$SCRIPT_DIR"
    
    # 查找匹配的标签
    local tag=$(git tag -l "kernel-v${version}*" | sort -V | tail -1)
    
    if [ -z "$tag" ]; then
        log_error "No tag found for version $version"
        return 1
    fi
    
    log_step "Switching to version: $version (tag: $tag)"
    
    git checkout "$tag"
    
    log_info "Switched to $tag"
}

# 推送标签到远程
push_tags() {
    local remote=${1:-"origin"}
    
    cd "$SCRIPT_DIR"
    
    log_step "Pushing tags to $remote..."
    
    git push "$remote" --tags
    
    log_info "Tags pushed successfully"
}

# 比较两个版本
compare_versions() {
    local v1=$1
    local v2=$2
    
    if [ -z "$v1" ] || [ -z "$v2" ]; then
        log_error "Please specify two versions to compare"
        return 1
    fi
    
    cd "$SCRIPT_DIR"
    
    local tag1=$(git tag -l "kernel-v${v1}*" | sort -V | tail -1)
    local tag2=$(git tag -l "kernel-v${v2}*" | sort -V | tail -1)
    
    if [ -z "$tag1" ] || [ -z "$tag2" ]; then
        log_error "Tags not found for one or both versions"
        return 1
    fi
    
    log_info "Comparing $tag1 vs $tag2..."
    echo ""
    
    git log --oneline "$tag1..$tag2"
    
    echo ""
    echo "Files changed:"
    git diff --stat "$tag1" "$tag2"
}

# 显示版本信息
show_info() {
    local version=$(get_current_version)
    local current_branch=$(cd "$SCRIPT_DIR" && git branch --show-current)
    local current_tag=$(cd "$SCRIPT_DIR" && git describe --tags --abbrev=0 2>/dev/null || echo "none")
    
    echo ""
    echo "=== Version Information ==="
    echo "Current kernel version: $version"
    echo "Current branch: $current_branch"
    echo "Current tag: $current_tag"
    echo ""
    echo "Kernel source directory: $KERNEL_SRC"
    
    if [ -d "$KERNEL_SRC/.git" ]; then
        cd "$KERNEL_SRC"
        echo "Kernel source has git history"
        echo "Last commit: $(git log -1 --oneline)"
    else
        echo "Kernel source is not a git repository"
    fi
    
    echo ""
}

# 主函数
main() {
    local action=${1:-"info"}
    
    case "$action" in
        list)
            list_versions
            ;;
            
        tag)
            create_tag "$2" "$3"
            ;;
            
        branch)
            create_branch "$2"
            ;;
            
        switch)
            switch_version "$2"
            ;;
            
        push)
            push_tags "$2"
            ;;
            
        compare)
            compare_versions "$2" "$3"
            ;;
            
        info)
            show_info
            ;;
            
        *)
            echo "Git Version Manager for SukiSU Kernel"
            echo ""
            echo "Usage: $0 <command> [options]"
            echo ""
            echo "Commands:"
            echo "  info                  Show version information (default)"
            echo "  list                  List all version tags"
            echo "  tag [ver] [msg]       Create version tag"
            echo "  branch <ver>          Create version branch"
            echo "  switch <ver>          Switch to specific version"
            echo "  push [remote]         Push tags to remote"
            echo "  compare <v1> <v2>     Compare two versions"
            exit 1
            ;;
    esac
}

main "$@"